### ISSUE TITLE
`iron-page-url` dependency points to branch, should be a stable released version

### ISSUE THREAD

**Issue by cdata** [PolymerElements/carbon-route#21]
Currently, the `iron-page-url` dependency in `bower.json` points to a WIP branch called `iron-query-params`. For release, I propose that we change this to point to a specific semver release of `iron-page-url`. In order to accomplish this, we should get https://github.com/PolymerElements/iron-page-url/tree/iron-query-params merged into `master` on that repo ASAP.

**Comment by rictic** [comment]
This is now fixed, we point to the v0.8 release of iron-location (nee iron-page-url)
