### ISSUE TITLE
Discussion: should the zero value for `queryParams` be `null` or `{}`?

### ISSUE THREAD

**Issue by cdata** [PolymerElements/carbon-route#28]
This is an open design question that has not settled. Please discuss pros, cons and alternatives in this issue.

**Comment by cdata** [comment]
Does this need more discussion? Have we landed on `{}`?

**Comment by e111077** [comment]
I think we did land on `{}` [source](https://github.com/PolymerElements/iron-location/blob/master/iron-query-params.html#L29)

**Comment by cdata** [comment]
I'm gonna close this, since it seems resolved. We can re-open if it isn't :octopus:
