### ISSUE TITLE
Import the url-bar element somewhere and use it in all of our carbon-route and iron-location demos

### ISSUE THREAD

**Issue by rictic** [PolymerElements/carbon-route#46]
The url-bar element from the carbon-route explainer is useful for our demos. It detects when it's running in an iframe and draws a helpful read-only live view of the URL bar. When it's not running in an iframe it's invisible.

We should import it into iron-demo-helpers or someplace similar and use it in these demos and in the iron-location demos.

**Comment by cdata** [comment]
Is it useful for non-`carbon-route` demos?

**Comment by e111077** [comment]
I can see this being used in demos that use iron-location and demos that are using `carbon-route` but not really outside of the `carbon-route` sphere of influence.

**Comment by rictic** [comment]
It's useful for any element that interacts with the URL bar. It's true that for the polymer team's elements that's probably going to be just carbon-route and iron-location, but I can see it being useful for app authors making demos for their elements.
