### ISSUE TITLE
Add Carbon Elements to https://elements.polymer-project.org/

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/carbon-route#57]
Subject says it all. It would be nice to find Carbon elements on elements.polymer-project.org

**Comment by e111077** [comment]
Heya @kenchris! We intend on adding Carbon Elements to the elements page once we have a stable version out. We want to make sure that the community knows that `carbon-route` is still in alpha and the API is still subject to possible changes.

**Comment by rictic** [comment]
We're calling out the fact that it's a beta release in enough places that I think it's ok to land in the elements catalog. I believe that Chris was onboard for that as well, so I think this is going ahead after all.

**Comment by rictic** [comment]
It's live on elements.polymer-project.org!
