### ISSUE TITLE
Object.assign does not work in IE

### ISSUE THREAD

**Issue by keanulee** [PolymerElements/carbon-route#73]
### Description
`Object.assign` is used in <carbon-route>.__routeQueryParamsChanged, which is not supported in IE11 (ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign). Is there an alternative we can use?

### Expected outcome

Router should work in IE11.

### Actual outcome

Router doesn't work in IE11.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [x] IE 10

**Comment by e111077** [comment]
Fixed in

https://github.com/PolymerElements/carbon-route/issues/65
