### ISSUE TITLE
Opening a path and redirecting in an observer won't update the location bar 

### ISSUE THREAD

**Issue by timeu** [PolymerElements/carbon-route#74]
### Description

Not sure if this is by design or a known issue. I put `carbon-route` and `carbon-location` into a custom element. I added a `observer` to check if the `page` parameter is valid and if not I reset it, so that the user is redirected to a valid path. 

So if I open the path: `http://localhost:8000/some_invalid_path` I should get redirected to `http://localhost:8000`

### Expected outcome

Browser location bar should be updated

### Actual outcome

Browser location bar is NOT updated

### Live Demo

I am not sure how to do a demo in jsbin

### Steps to reproduce

```html
<dom-module id="my-router">
  <template>
      <carbon-location route="{{route}}" ></carbon-location>
      <carbon-route
            route="{{route}}"
            pattern="/:step"
            data="{{page}}"
            tail="{{tail}}">
      </carbon-route>
  </template>
  <script>
    (function() {
      'use strict';
      Polymer({
        is: 'my-router',
        properties: {
            page: {
                type:Object,
                value: function(){ return {};},
            },
        },
        observers: [
          '_changeRoute(page)',  
        ],
        _changeRoute: function(page) {
           // check if page is valid if not redirect
            this.page = {};
        },
      });
    })();
  </script>
</dom-module>
```
As far as I can tell the reason is that in the [_updateUrl](https://github.com/PolymerElements/iron-location/blob/master/iron-location.html#L199) method in `iron-location` the flag `_initialized` is false because `iron-location` has not been attached yet. 
The only workaround is to use `async`: 

```javascript
_changeRoute: function(page) {
      // check if page is valid if not redirect
      this.async(function() {
          this.page = {};
      });
 },
```
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rictic** [comment]
Confirmed that this is a real bug and not intended behavior. I'm working on this issue this week. We've got this filed as #44.
