### ISSUE TITLE
Updating data property of subroute won't propagate when subroute is not active

### ISSUE THREAD

**Issue by timeu** [PolymerElements/carbon-route#75]
### Description

Not sure if by design or a known limitation: 

I have a parent route with a `:page` data property and a subroute with an `:id` property.
```html
<carbon-location route="{{route}}"></carbon-location>
<carbon-route
    route="{{route}}"
    pattern="/:page"
    data="{{routeData}}"
    tail="{{subroute}}">
</carbon-route>
<carbon-route id="subrouter"
    route="{{subroute}}"
    pattern="/:id"
    data="{{subrouteData}}">
</carbon-route>
``` 
If I update the `data` property of a subroute the browser location bar won't propagate, if the subroute is not active/matched. 

### Expected outcome

Original URL: http://localhost:8000/somePage 

```javascript
this.$.subrouter.data =  {id:2};
```
New URL: http://localhost:8000/somePage/2

### Actual outcome

Original URL = New URL =  http://localhost:8000/somePage 

### Reason

This seems to be due to the fact that the subroute is not active and [__updatePathOnDataChange](https://github.com/PolymerElements/carbon-route/blob/master/carbon-route.html#L305) will bail out early.

Workaround:

change the `tail.path` of the parent `carbon-route` instead of the `data` property of the subroute.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by TimvdLippe** [comment]
It should work if you use a trailing slash? `http://localhost:8000/somePage/`

This is indeed confusing and I also encountered with the matching in that sense

**Comment by timeu** [comment]
Yeah a trailing slash fixes it. 
However IMHO this is not really a satisfying solution because I don't have a control of which URL users puts into the browser location bar and I want to avoid some brittle workaround to add a trailing slash to every URL. 

Also the `carbon-router` itself does not add any trailing slashes itself, so if I want to navigate to a sub-route it won't work. Let's assume that the user starts at: 

http://localhost:8000/ 

Then I through databinding on the root `carbon-router`  I change the `page` property to `users`. This will change the browser location bar to: 

http://localhost:8000/users  (note the missing trailing slash)

Now if I want to navigate to the detail page (i.e. http://localhost:8000/users/2) through data-binding on the `id` property of the sub `carbon-router` it does not work because of the missing trailing slash.

Maybe I am missing something obvious here.

**Comment by TimvdLippe** [comment]
Yes I encountered this too and I think issue #37 is designated to fix/clear up this behavior.

**Comment by rictic** [comment]
As designed, changes to data on inactive routes don't propagate. The thinking here is that this is the less surprising thing, as it would be easy to get into a situation where changing a property that happens to be bound into a distant `carbon-route` could end up with an unexpected redirect.

The subtle distinctions between `/foo`, `/foo/` and `/foo/bar` here aren't great though. As Tim mentioned we're tracking that at #37 while we consider solutions.
