### ISSUE TITLE
Unable to post stackoverflow questions because carbon-route tag does not exist

### ISSUE THREAD

**Issue by exgalexo** [PolymerElements/carbon-route#80]
### Description
In the Polymer routing guide, it mentions that questions tagged "carbon-route" on stackoverflow will be watched:
https://www.polymer-project.org/1.0/articles/routing.html

However, I am not able to tag questions with this tag because the tag does not yet exist, and at least 1500 reputation is required to create a new tag (e.g. currently I only have ~150 reputation).

### Expected outcome

It should be possible to tag stackoverflow.com questions with carbon-route without requirement for 1500 reputation.

### Actual outcome

It is not possible to tag a stackoverflow.com question with carbon-route without having at least 1500 reputation.

### Live Demo

The question that I'd like to tag with carbon-route is:
https://stackoverflow.com/questions/36670748/activating-default-route-if-no-other-carbon-route-active

### Steps to reproduce

1. go to https://stackoverflow.com/questions/36670748/activating-default-route-if-no-other-carbon-route-active
2. log in with account that has less than 1500 repuation
3. add a tag of "polymer-route"

### Browsers Affected
all

**Comment by rictic** [comment]
Thanks for filing this bug report! I added the carbon-route tag to your question and created the tag.
