### ISSUE TITLE
observers in `carbon-route` break when compiling the Javascript with Closure compiler.

### ISSUE THREAD

**Issue by palli** [PolymerElements/carbon-route#91]
### Description
When the `carbon-route` element is present on a page, it will not work as expected after the code has been compiled with jscompiler and instead prints error to the JS console.

Curiously, when removing some of the observers from the observer list, say `__updatePathOnDataChange()` the code works fine and everything gets minimized correctly.

I think this might be related to either the deep inspections, or the fact that the signature of the observers does not match what what the compiled expects (some of the observers don't take the changed data as an argument).

### Expected outcome
Page should load error free. and the code should be minimized both for the functions and 

### Actual outcome

The functions get minimized, but the string definitions inside the observers property do not.

The following errors get printed to the console:

```
[carbon-route::_complexObserverEffect]: observer method `__updatePathOnDataChange` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__queryParamsChanged` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__tailPathChanged` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__tailQueryParamsChanged` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__tryToMatch` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__tryToMatch` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__routeQueryParamsChanged` not defined
app.js:4384 [carbon-route::_complexObserverEffect]: observer method `__updatePathOnDataChange` not defined
```
### Browsers Affected
Tested on chrome, but considering the nature of the bug I expect all browsers.

### Other

Curiously, when removing some of the observers from the list, everything will get minimized as expected. For example removing observer `__updatePathOnDataChange` will cause the observers property to get minimized to this:

```
observers:["yE(route.path,pattern)","wE(tail.path)","vE(route.__queryParams)","xE(tail.__queryParams)","tE(queryParams.*)"]
```

Which will load error free.

Similarly removing `__queryParamsChanged` will also cause the code to compile free, which might suggest a compiler bug, but I am not sure what exactly makes this component special in that way.

**Comment by rictic** [comment]
This should be fixed now.
