### ISSUE TITLE
Default redirect page for home

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/carbon-route#97]
### Description
Applications have a default page when you initially open the website. For example instead of `localhost:8080/` the user should see `localhost:8080/my/home/page` as home page url.

It would be better if this could be directly integrated into the `<carbon-location>` by adding a property `fallback="art` which will set the `route.path` to the corresponding.

### Usage
```html
<carbon-location fallback="my/home/page"></carbon-location>
```

When the user visits `localhost:8080/` `<carbon-location` will modify the route to `localhost:8080/my/home/page` and update the url and data-bindings accordingly.
If the user visits `localhost:8080/existing/page` the url remains unmodified.

**Comment by rictic** [comment]
My intuition is that this is better encoded as a bit of logic on the app element.

Some apps want to redirect `/` to `/my/home/page`, some want to redirect `/user/` to `/user/profile` but not redirect `/user/alice`, etc etc etc.

Adding this to carbon-location is more complexity on the element, and may communicate that redirecting is special and needs to be handled by special routing code. This is already something of a problem today,  and something I think we should really endeavor to minimize.

**Comment by TimvdLippe** [comment]
The intention was to only support redirects from `/`, not redirects in general. Therefore it should not do anything for `/user/` or any route in general which is not `/`.

**Comment by rictic** [comment]
My point with the `/user` -> `/user/profile` example is just that there are a lot of redirection use cases, and it's not clear to me why we should bake in special handling for the use case of redirecting away from `/`
